export const GET_ALL_EMPLOYEES: string="GET_ALL_EMPLOYEERS";
export const GET_ALL_EMPLOYEES_LOADING: string="GET_ALL_EMPLOYEERS_LOADING";


export const GET_SINGLE_EMPLOYEE_LOADING: string="GET_SINGLE_EMPLOYEE_LOADING";
export const GET_SINGLE_EMPLOYEE: string="GET_SINGLE_EMPLOYEE";

export const SEARCH_EMPLOYEE: string="SEARCH_EMPLOYEE";

export const GET_PROJECTS_OF_EMPLOYEE='GET_PROJECTS_OF_EMPLOYEE'
export const GET_PROJECTS_OF_EMPLOYEE_LOADING='GET_PROJECTS_OF_EMPLOYEE_LOADING'


